### PR TITLE
Upgrade deps, refactor babel

### PR DESCRIPTION
**Pull request by landonreed**

### CODE REVIEW

**Comment by landonreed** [comment]
Whoa, nice side effect!

**Comment by landonreed** [comment]
Before we merge, I want to test this code on IE 11, just to make sure nothing is broken there.

**Comment by landonreed** [comment]
I guess the app is already broken for IE11 (see #226), so maybe we ought to fix that first and then check that this branch is OK.

**Comment by evansiroky** [comment]
@landonreed, any updates? We should get this merged and deployed soon since it fixes a few bugs with the otp-rr upgrade.

**Comment by landonreed** [comment]
No updates yet on IE fixes, but yea, let's go ahead and merge for now.

**Pull request merged**
