### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by landonreed**
Just noticed this was missing.

### CODE REVIEW

**Comment by evansiroky** [comment]
This change needs to be agreed upon by all people who have contributed to this project so far. I agree, however, @fpurcell and @demory must also explicitly agree to have their contributions be licensed this way.

**Comment by fpurcell** [comment]
+1 on adding the MIT license w/IBI as copyright holder

**Comment by landonreed** [comment]
@demory, do you have any comments on what the license here should be or thoughts on who the copyright holder should be?

**Comment by landonreed** [comment]
Closing given that this is pretty stale and this repo is expected to be phased out at some point in the near future.

**Pull request closed without merging**
